export const RadioSt = [
    ['60','https://radio.streamgates.net/stream/galil','רדיו קול הגליל העליון 105.3FM'],
    ['23','https://radio.streamgates.net/stream/KOLREGA','רדיו קול רגע'],
    ['50','http://sweb.co.il:7777/;','רדיו לב הפסגה'],
    ['45','https://cdn.cybercdn.live/Pervoia/Audio/icecast.audio','Первое радио 89.1FM'],
    ['46','http://194.153.101.160:8000/idc123.mp3','הרדיו הבינתחומי'],
    ['19','http://106fm.livecdn.biz:7075/;stream.mp3','קול הקמפוס 106FM'],
    ['58','http://hyades.shoutca.st:8735/;','רדיו רנסאנס'],
    ['30','http://uk2-vn.mixstream.net:8004/stream/1/','רדיו קול השלום'],
    ['35','https://radio.streamgates.net/stream/netanya','רדיו קול נתניה 106FM'],
    ['70','http://radio.ilcast.com:8000/live','RADIO 69FM'],
    ['53','http://cp11.livecdn.biz/radiodance_aac','radioDANCE'],
    ['73','https://cdna.streamgates.net/TheBest/live/playlist.m3u8','Лучшее Радио'],
    ['56','http://185.80.220.12:8047/stream','רדיו רן (פרסית)'],
    ['2','https://radio.streamgates.net/stream/90fm','רדיו תשעים'],
    ['68','http://radio.eretz.fm/eretz-mp3','רדיו ארץ'],
    ['33','http://sweb.co.il:8008/;','רדיו חולמים מזרחית'],
    ['43','https://radio.streamgates.net/stream/1036','קול רמת השרון'],
    ['14','https://audio-darom.ecast.co.il/darom97fm','רדיו דרום'],
    ['38','http://84.94.229.99:5998/;','רדיו חוף אילת'],
    ['7','https://eco-live.mediacast.co.il/99fm_aac','רדיו 99FM'],
    ['3','https://acdn.streamgates.net/91fm','רדיו לב המדינה'],
    ['1','https://kanliveicy.media.kan.org.il/icy/kan88_mp3?providername=coolsite','כאן 88'],
    ['27','https://radio.streamgates.net/stream/eilat','רדיו קול הים האדום'],
    ['5','https://acdn.streamgates.net/100fm','רדיוס 100FM'],
    ['54','http://www.breslav.co.il:5555/;','רדיו ברסלב - קול הנחל'],
    ['61','http://178.63.110.13:37600/stream','רדיו רוח מזרחית'],
    ['57','https://ssl.shoutcaststreaming.us:8061/;','רדיו המזרח'],
    ['32','https://radio.streamgates.net/stream/kinneret','רדיו קול הכנרת'],
    ['26','https://kanliveicy.media.kan.org.il/icy/kankolhamusica_mp3?providername=coolsite','כאן קול המוסיקה'],
    ['36','http://770tv.no-ip.org:7777/;','רדיו מבשר טוב'],
    ['55','https://icecast.myradio.co.il/livegreece','רדיו כחול יוון'],
    ['47','https://audio-darom.ecast.co.il/darom101','רדיו דרום 101.5'],
    ['10','https://kanliveicy.media.kan.org.il/icy/kanbet_mp3?providername=coolsite','כאן ב'],
    ['71','https://radio.streamgates.net/stream/1036kh','רדיו קול השפלה'],
    ['62','https://radio.streamgates.net/stream/1045fm','רדיו צפון 104.5'],
    ['4','https://102.livecdn.biz/102fm_mp3','רדיו תל אביב 102FM'],
    ['21','http://media2.93fm.co.il/live','רדיו קול חי'],
    ['59','http://kzradio.mediacast.co.il/kzradio_live/kzradio/icecast.audio','רדיו הקצה'],
    ['18','https://media-ssl.musicradio.com/ClassicFM','Classic FM'],
    ['67','https://securestreams2.autopo.st:1242/live','BeatFM'],
    ['39','https://radio.streamgates.net/stream/sol','רדיו סול'],
    ['75','https://icecast.myradio.co.il/zerock','רדיו זה רוק'],
    ['11','http://1075.livecdn.biz/radiohaifa','רדיו חיפה'],
    ['66','https://liveradio.co.il/wet','רדיו מרטיט מיתר בלב'],
    ['65','http://radio.ilcast.com:8052/;','רדיו קול עכו'],
    ['29','https://audio-darom.ecast.co.il/live','רדיו גלי ישראל'],
    ['74','https://kanliveicy.media.kan.org.il/icy/kanreka_mp3?providername=coolsite','כאן רקע'],
    ['44','http://cuead.cdnwiz.com/cuead-109fmmp3-64','רדיו 109FM'],
    ['64','http://streaming.radionomy.com/GoldRadioIsraelOfficiel','GOLD Radio Israel'],
    ['52','http://gb35.streamgates.net/ariel106fm/audio/icecast.audio','רדיו קול אחר 106FM'],
    ['6','http://glzwizzlv.bynetcdn.com/glz_mp3','גלי צהל'],
    ['69','http://sweb.co.il:8014/;stream.mp3','רדיו חנה'],
    ['37','http://listen.clickfm.co.il/1FM','רדיו 1FM'],
    ['42','http://icecast.kab.tv/heb.mp3','רדיו קבלה FM'],
    ['40','http://radio-yasoo.ath.cx:7500/;','רדיו יאסו'],
    ['48','https://diki.mediacast.co.il/diki','רדיו שירי דיכאון'],
    ['24','https://rs.mizrahit.fm:7777/;','רדיו נושמים מזרחית'],
    ['8','http://glzwizzlv.bynetcdn.com/glglz_mp3','גלגלצ'],
    ['51','https://rdm.mediacast.co.il:7777/radiom','רדיו מזרחית'],
    ['31','https://radio.streamgates.net/stream/kbmusic','רדיו קול ברמה'],
    ['17','https://yamfm.mediacast.co.il/yamfm?type=.mp3','רדיו קליק לים התיכון'],
    ['16','https://kanliveicy.media.kan.org.il/icy/kangimmel_mp3?providername=coolsite','כאן גימל'],
    ['15','https://radio.streamgates.net/stream/hatahana','רדיו התחנה 101.5'],
    ['20','https://kanliveicy.media.kan.org.il/icy/kanmoreshet_mp3?providername=coolsite','כאן מורשת'],
    ['13','http://www.menta-fm.co.il:8888/','רדיו קול המזרח'],
    ['9','https://acdn.streamgates.net/103fm','רדיו 103'],
    ['41','https://eol-live.cdnwiz.com/eol/eolsite/icecast.audio','רדיו מהות החיים'],
    ['28','https://kanliveicy.media.kan.org.il/icy/kantarbut_mp3?providername=coolsite','כאן תרבות'],
    ['25','https://radio.streamgates.net/stream/101fm','רדיו ירושלים'],
    ['63','https://ice66.securenetsystems.net/CJRT?playSessionID=DE5AE27F-E75A-A794-60CE6AAFACB933A1','Jazz FM'],
    ['12','https://liveradio.co.il/radiolove','רדיו שירי אהבה'],
    ['34','http://freeuk3.listen2myradio.com:18186/;','רדיו קול המרכז'],
    ['49','http://www.radio-beat.com/server1','רדיו ביט']
];
